spring.profiles.active=${ENV:dev}

# Application Name
spring.application.name=Chanakya Backend

# Server Configuration
server.port=${PORT:8080}
server.servlet.context-path=/api
spring.jackson.serialization.write-dates-as-timestamps=false 
