package com.chanakya.dto;

import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AssessmentRequest {

    @NotNull(message = "Answers cannot be null")
    private Map<String, Object> answers;  // QuestionId -> Answer mapping

    // Getter and setter are generated by @Data
    // So getAnswers() method will be available
}